### ISSUE TITLE
Change the position of 'Add your quote here...' and its button to be after the quotes

### ISSUE THREAD

**Issue by kmi17** [kmi17/React-Quote-Sharing#2]
When there is at least one quote then change the position of the input box and button to display after the quotes. 

Reasoning:
When a user does not have any quotes, then we want the first action item to be sharing quotes. 
When a user does have a quote, then we want to display their content first and then everything else.

**Comment by GauravBahl** [comment]
Added the change.

**Comment by GauravBahl** [comment]
Added the change.

**Comment by kmi17** [comment]
looks good
